server:
  port: 8081
spring:
  application:
    name: ProductService
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        formatsql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: root
  config:
    import: configserver:http://localhost:9296
    
management:
   tracing:
    sampling:
      probability: 1.0

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
    



#server.port=8081
#spring:application:name:ProductService
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url = jdbc:postgresql://localhost:5432/product_db
#spring.datasource.username = postgres
#spring.datasource.password = root
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true.
