#spring.application.name=OrderServic
server:
  port: 8083
spring:
  application:
    name: OrderService
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        formatsql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: root
  config:
    import: configserver:http://localhost:9296
      
management:
   tracing:
    sampling:
      probability: 1.0


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}